---
# tasks file for mysql role

- name: update the cache
  apt: update_cache=yes
- name: instalation des packages
  package:
    name={{mysql_packages}}
    state=installed
- name: Ensure MySQL is started and enabled on boot.
  service:
    name=mysql
    state=started
    enabled=yes
- name: update mysql root password
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
      - 127.0.0.1
      - ::1
      - localhost
- name: Copy .my.cnf
  template:
    src=my.cnf
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
- name: delete MYQL anonymous user
  mysql_user:
    name=""
    state="absent"
- name: Remove mysql test database
  mysql_db:
    name="test"
    state="absent"
